#!/bin/bash

clear

echo -n "Enter Number: "
read n

sd=0
rev=0
on=$n

while [ $n -gt 0 ]
do
    sd=$((n % 10))
    n=$((n / 10))
    rev=$((rev * 10 + sd))
done

if [ $on -eq $rev ]
then
    echo "Number $on is a Palindrome"
else
    echo "Number $on is NOT a Palindrome"
fi
